AllCops:
  Exclude:
  # Rubocop defaults
  - Gemfile
  - vendor/**/*
  - tmp/**/*
  # Framework generated configuration files
  - config/boot.rb
  - config/application.rb
  - config/environment.rb
  - config/puma.rb
  - config/spring.rb
  - config/environments/development.rb
  - config/environments/production.rb
  - config/environments/test.rb
  - config/initializers/assets.rb
  - config/initializers/backtrace_silencers.rb
  - config/initializers/cookies_serializer.rb
  - config/initializers/filter_parameter_logging.rb
  - config/initializers/inflections.rb
  - config/initializers/mime_types.rb
  - bin/**/*
  - script/**/*
  - db/schema.rb
 # rspec generated files
  - spec/spec_helper.rb
  - spec/rails_helper.rb

